/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_installedapps_com_installedapps_xposed_XposedPermissionSettings */

#ifndef _Included_com_installedapps_com_installedapps_xposed_XposedPermissionSettings
#define _Included_com_installedapps_com_installedapps_xposed_XposedPermissionSettings
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_installedapps_com_installedapps_xposed_XposedPermissionSettings
 * Method:    grantPermission
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_installedapps_com_installedapps_xposed_XposedPermissionSettings_grantPermission
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_installedapps_com_installedapps_xposed_XposedPermissionSettings
 * Method:    revokePermission
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_installedapps_com_installedapps_xposed_XposedPermissionSettings_revokePermission
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_installedapps_com_installedapps_xposed_XposedPermissionSettings
 * Method:    queryPermission
 * Signature: (Ljava/lang/String;C)I
 */
JNIEXPORT jint JNICALL Java_com_installedapps_com_installedapps_xposed_XposedPermissionSettings_queryPermission
  (JNIEnv *, jclass, jstring, jchar);

/*
 * Class:     com_installedapps_com_installedapps_xposed_XposedPermissionSettings
 * Method:    runServer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_installedapps_com_installedapps_xposed_XposedPermissionSettings_runServer
        (JNIEnv *, jclass);

/*
 * Class:     com_installedapps_com_installedapps_xposed_XposedPermissionSettings
 * Method:    killServer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_installedapps_com_installedapps_xposed_XposedPermissionSettings_killServer
        (JNIEnv *, jclass);

/*
 * Class:     com_installedapps_com_installedapps_xposed_XposedPermissionSettings
 * Method:    init
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_installedapps_com_installedapps_xposed_XposedPermissionSettings_init
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
